---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx-ingress
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./gitops/infra/ingress-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
