---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: logs-scrape
  namespace: flux-system
spec:
  dependsOn:
    - name: metrics
  interval: 1m0s
  path: ./gitops/infra/logs/scrape
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
