---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metrics-scrape
  namespace: flux-system
spec:
  dependsOn:
    - name: metrics
  interval: 1m0s
  path: ./gitops/infra/monitoring/scrape
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
