alertmanager:
  config:
    global:
      resolve_timeout: 5m
      smtp_smarthost: smtp.example.com:25
      smtp_from: 'Alertmanager <admin@it-lux.ru>'
    templates:
      - "/etc/vm/configs/**/*.tmpl"
    route:
      group_by: ["alertgroup", "job"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: "send_email"
      routes:
        - matchers:
            - severity=~"info|warning|critical"
          receiver: send_email
    receivers:
      - name: send_email
        email_configs:
        - to: your_email@examle.ru
          send_resolved: true
          auth_username: your_email@examle.ru
          auth_password: <strong_pass>
          require_tls: false
