---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  targetNamespace: metrics
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: 0.8.3
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
  valuesFrom:
    - kind: ConfigMap
      name: victoria-metrics-values
    - kind: ConfigMap
      name: alertmanager-config-values
