
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrics
resources:
  - helm-repository.yaml
  - helm-release.yaml
  - namespace.yaml
  - dashboards
configMapGenerator:
  - name: victoria-metrics-values
    files:
      - values.yaml=values.yaml
  - name: alertmanager-config-values
    files:
      - values.yaml=alertmanager-config-values.yaml
configurations:
  - kustomizeconfig.yaml
